name: Release

on:
  # Run the workflow each time new commits are pushed to the candidate branch.
  push:
    branches: ["preview/candidate"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  get-architectures:
    name: ðŸ–¥ Get snap architectures
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.get-architectures.outputs.architectures }}
      architectures-list: ${{ steps.get-architectures.outputs.architectures-list }}
    steps:
      - name: ðŸ–¥ Get snap architectures
        id: get-architectures
        uses: snapcrafters/ci/get-architectures@main

  release:
    name: ðŸš¢ Release to preview/candidate
    needs: get-architectures
    runs-on: ubuntu-latest
    environment: "Preview Candidate Branch"
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-architectures.outputs.architectures-list) }}
    steps:
      - name: ðŸš¢ Release to preview/candidate
        uses: snapcrafters/ci/release-to-candidate@main
        with:
          architecture: ${{ matrix.architecture }}
          channel: preview/candidate
          launchpad-token: ${{ secrets.LP_BUILD_SECRET }}
          repo-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}

  call-for-testing:
    name: ðŸ“£ Create call for testing
    needs: [release, get-architectures]
    environment: "Preview Candidate Branch"
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.issue.outputs.issue-number }}
    steps:
      - name: ðŸ“£ Create call for testing
        id: issue
        uses: snapcrafters/ci/call-for-testing@main
        with:
          architectures: ${{ needs.get-architectures.outputs.architectures }}
          channel: preview/candidate
          github-token: ${{ secrets.GITHUB_TOKEN }}
          promotion-channel: preview/stable

  screenshots:
    name: ðŸ“¸ Gather screenshots
    needs: call-for-testing
    environment: "Preview Candidate Branch"
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¸ Gather screenshots
        uses: snapcrafters/ci/get-screenshots@main
        with:
          channel: preview/candidate
          issue-number: ${{ needs.call-for-testing.outputs.issue-number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          screenshots-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
